config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to:'pages#about'

  resources :articles
  
  get 'signup', to: 'users#new' 
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: {minimum: 10, maximum:1000}
    validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
    belongs_to :article
    belongs_to :category

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles, dependent: :destroy
    before_save { self.email = email.downcase}
    validates :username, presence: true, 
                        uniqueness: { case_sensitive: false }, 
                        length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
                    uniqueness: { case_sensitive: false }, 
                    length: {maximum: 105},
                    format: { with: VALID_EMAIL_REGEX }
    has_secure_password            
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform that action"
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy ]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def index
        @articles= Article.paginate(page: params[:page], per_page: 4)
    end

    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article was successfully created"
            redirect_to article_path(@article)
        else
            render 'new' 
        end

    end

    def update
        if @article.update(article_params)
            flash[:success] ="Article was successfully edited"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def show
    end

    def destroy
        @article.destroy
        flash[:danger] = "Article was successfully deleted"
        redirect_to articles_path
    end

    private
        def set_article
            @article = Article.find(params[:id])
        end
        
        def article_params
            params.require(:article).permit(:title, :description, category_ids: [])
        end

        def require_same_user
            if current_user != @article.user and !current_user.admin?
                flash[:danger] = "You can only edit or delete your own articles"
                redirect_to root_path
            end
        end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :require_admin, except: [:index, :show]
    def index
        @categories = Category.paginate(page: params[:page], per_page: 4)
    end

    def new
        @category = Category.new
    end

    def create
        @category =Category.new(category_params)
        if @category.save
            flash[:success] = "Category was successfully created"
            redirect_to categories_path
        else
            render 'new'
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params) 
            flash[:success] = "Category name was successfully updated"
            redirect_to category_path(@category)
        else
            render 'edit'
        end
    end
    
    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

    private
        def category_params
            params.require(:category).permit(:name)
        end

        def require_admin
            if !logged_in? || (logged_in? and !current_user.admin)
                flash[:danger] = "Only admin can perform that action"
                redirect_to categories_path
            end
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
          session[:user_id]=user.id
          flash[:success] = "Successfully logged in"
          redirect_to user_path(user)  
        else
            flash.now[:danger] ="Something went wrong!"
            render 'new' 
        end
    end

    def destroy
        session[:user_id] = nil 
        flash[:success] = "Successfully Logged out"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]
    def index
        @users =User.paginate(page: params[:page], per_page: 4)
    end
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to the Journal Blog #{@user.username}"
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:success] = "Your account was updated successfully"
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    def show
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 4)
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "User and all Articles created by user have been deleted"
        redirect_to users_path
    end

    private
        def set_user
            @user = User.find(params[:id])
        end
        
        def user_params
            params.require(:user).permit(:username, :email, :password)
        end

        def require_same_user
            if current_user != @user and !current_user.admin?
                flash[:danger] ="You can only edit your own account"
                redirect_to root_path
            end
        end

        def  require_admin
            if logged_in? and !current_user.admin?
                flash[:danger] = "Only admin users can perform that action"
                redirect_to root_path
            end
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id =Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url ="https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
    end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card">
            <div class="article-title">
                <%= link_to article.title, article_path(article) %>
            </div>

            <div class="article-body">
                <%= truncate(article.description, length: 200) %>
                <div class="article-meta-details">
                    <div class="row">
                        <div class="col-md-5">
                            <% if article.categories.any? %>
                                <small><p>Categories: <%= render article.categories %></p></small>
                            <% end %>
                        </div>
                        
                        <div class="col-md-7">
                            <small>Created By: <%= article.user.username if article.user %>,
                                            <%= time_ago_in_words(article.created_at) %> ago,
                                            last updated: <%= time_ago_in_words(article.updated_at) %> ago
                            </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </br>
    </div>
</div>
<%end%>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article%>
    <div class="col-xs-12">
        <%= form_for @article do |f| %>
            <div class="form-group row">
                <div class="control-label col-sm-2">
                    <%= f.label :Title %>
                </div>
                <div class="col-sm-8">
                <%= f.text_field :title, class:"form-control", placeholder:"Title of Article", autofocus: true %>
                </div>
            </div>

            <div class="form-group row">
                <div class="control-label col-sm-2">
                    <%= f.label :Description %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_area :description, rows: 10, class:"form-control", placeholder: "Wirte your article here...", autofocus:true %>
                </div>
            </div>

            <div class="form-group row">
                <div class="control-label col-sm-2">
                    <%= f.label :Category %>
                </div>
                <div class="col-sm-8">
                    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                        <% cb.label(class: "checkbox-inline input-checkbox mr-3") {cb.check_box(class: "checkbox mr-1") + cb.text} %>
                    <%end%>
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-md-12">
                <%= link_to 'Go Back', articles_path, class:'btn btn-warning btn-md offset-2'%>
                <%= link_to 'CANCEL', new_article_path, class:'btn btn-danger btn-md offset-5'%>
                <%= f.submit 'SUBMIT', class:'btn btn-info btn-md'%>
                </div>
            </div>

        <% end %>
        
    </div>

app/views/articles/index.html.erb
<h2 class="createheading"> ARTICLES </h2>
<br/>
<div>
    <%= render 'article', obj: @articles %>
</div>
<div class="offset-5 pl-4">
    <%= will_paginate %>
</div>

app/views/articles/show.html.erb
<div class="card col-md-10 offset-1">
    <h3 class="p-3 text-center card-title text-info border-bottom border-secondary"> 
        <%= @article.title %>
    </h3>
    
    <div class="card-body">
        <%= simple_format(@article.description) %>
        
            
        
            <% if @article.user %>
                <ul class="listing">
                    <div class="row">

                        <% if @article.categories.any? %>
                        <div class="col-md-6 text-center">
                            <li>
                                <p>Categories: <%= render @article.categories %></p>
                            </li>
                        </div>
                        <% end %>

                        <div class="col-md-6 text-center">
                            <li class="article-title">
                                <small>Author : <%= link_to @article.user.username, user_path(@article.user) %>
                                </small>
                            </li>
                        </div>
                    </div>
                </ul>
            <%end%>
    </div>
</div>

<div class="article-actions">
    <%= link_to 'Go Back', articles_path, class:"btn btn-md btn-success offset-1"%>
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <%= link_to 'Delete', article_path(@article),
                            method: :delete, 
                            data: {confirm: "Are you sure? "}, 
                            class:"btn btn-md btn-danger offset-7"%>
    <%= link_to 'Edit Article', edit_article_path(@article), class:"btn btn-md btn-info"%> 
    <%end%>
</div>
</div>

app/views/categories/_category.html.erb
<span class="badge badge-secondary mr-1"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category%>
        <%= form_for @category do |f| %>
            <div class="form-group row">
                <div class="control-label col-sm-2">
                    <%= f.label :Name %>
                </div>
                <div class="col-sm-8">
                <%= f.text_field :name, class:"form-control", placeholder:"Enter category name", autofocus: true %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-md-12">
                <%= link_to 'CANCEL', categories_path, class:'btn btn-danger btn-md offset-5 mr-3'%>
                <%= f.submit(@category.new_record? ? "SUBMIT" : "UPDTAE", class:'btn btn-success btn-md')%>
                </div>
            </div>

        <% end %>

app/views/categories/edit.html.erb
<div class="text-center">
<h2 class="createheading"> EDIT CATEGORY </h2><br/>
</div>

<%= render 'form' %>

app/views/categories/index.html.erb
<h2 class="createheading"> CATEGORIES </h2>
<br/>
<div class="text-center">
    <% @categories.each do |category| %>
    <div class="row">
        <div class="col-md-4 offset-4 pt-3">
            <div class="card bg-light">
                <div class="article-title">
                    <%= link_to "#{category.name}", category_path(category) %>     
                </div>
                <small class="text-center">
                    <p>( <%= pluralize(category.articles.count, "Article") %> )</p>
                </small>
            </div>
        </div>
    </div>
    <% end %>
</div>

<div class="offset-5 pl-4 pt-5">
    <%= will_paginate %>
</div>

app/views/categories/show.html.erb
<h2 class="createheading"><%= "Category: " + @category.name %> </h2>
<br/>
<% if logged_in? and current_user.admin? %>
    <div class="float-right">
        <%= link_to "Edit Category Name", edit_category_path(@category), class:"btn btn-info"%>
    </div>
<% end %>
<div>
    <%= render 'articles/article', obj: @category_articles %>
</div>
<div class="offset-5 pl-4">
    <%= will_paginate @category_articles%>
</div>

app/views/layouts/_messages.html.erb
<br/>
<div class="row">
<div class="col-md-10 offset-1">
<% flash.each do |name,msg| %>
<div class='alert alert-<%="#{name}"%>'>
  <a href="#" class="close" data-dismiss="alert">&#215;</a>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>
</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbarbg">
  <%= link_to "Journal Blog", root_path, class:"navbar-brand", id:"logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Authors", users_path, class:"nav-link"%>
      </li>

    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Category
        </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All Categories", categories_path, class:"dropdown-item" %>
          <% Category.all.each do |category| %>
              <%= link_to "#{category.name}", category_path(category), class:"dropdown-item" %>
          <% end %>
          <% if logged_in? and current_user.admin? %>
          <div class="dropdown-divider"></div>
            <%= link_to "Add Category", new_category_path, class:"dropdown-item" %>
          <% end %>
      </div>
    </li>
    
    <% if logged_in? %>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "New Article", new_article_path, class:"dropdown-item" %>
          <%= link_to "Edit Article", articles_path, class:"dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "All Articles", articles_path, class:"dropdown-item" %>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile <%= "Admin" if current_user.admin?%>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Dashboard", user_path(current_user), class:"dropdown-item" %>
          <%= link_to "Edit Profile", edit_user_path(current_user), class:"dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Sign Out", logout_path, method: :delete, class:"dropdown-item" %>
        </div>
      </li>

    <% else %>

      <li class="nav-item">
        <%= link_to 'Login', login_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign up', signup_path, class:"nav-link"%>
      </li>

    <% end %>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages'%>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<h2>Hello About <h2>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="position-relative">
        <div class="homepageimage"></div>
        <div class="homeicons">
                <h1>JOURNAL BLOG <h1>
                <%= link_to 'Sign up', signup_path, class:"btn btn-info btn-lg"%>
        </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card bgerror text-danger">
            <div class="card-header">
                <h5 class="card-title">
                The following errors prevent the article from getting created:
                <%= pluralize(obj.errors.count,"error")%>
                </h5>
                    <div class="card-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg|%>
                                <li><%= msg %></li>
                            <%end%>
                        </ul>
                    </div>
            </div>
        </div>
    </div>
</div>
<br/>
<%end%>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user%>
    <div class="col-xs-12">
        <%= form_for @user do |f| %>
            <div class="form-group row">
                <div class="control-label col-sm-2">
                    <%= f.label :Username %>
                </div>
                <div class="col-sm-8">
                <%= f.text_field :username, class:"form-control", placeholder:"Enter username", autofocus: true %>
                </div>
            </div>

            <div class="form-group row">
                <div class="control-label col-sm-2">
                    <%= f.label :Email %>
                </div>
                <div class="col-sm-8">
                    <%= f.email_field :email, class:"form-control", placeholder: "Enter email", autofocus:true %>
                </div>
            </div>

            <div class="form-group row">
                <div class="control-label col-sm-2">
                    <%= f.label :Password %>
                </div>
                <div class="col-sm-8">
                    <%= f.password_field :password, class:"form-control", placeholder: "Enter password", autofocus:true %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-md-12">
                <%= link_to 'CANCEL', root_path, class:'btn btn-danger btn-md offset-5 mr-3'%>
                <%= f.submit(@user.new_record? ? "SUBMIT" : "UPDATE", class:'btn btn-success btn-md')%>
                </div>
            </div>

        <% end %>
        
    </div>

app/views/users/edit.html.erb
<h2 class="text-center">Edit Account</h2>
<%= render 'form' %>

app/views/users/new.html.erb
<h2 class="text-center">SIGNUP</h2>
<%= render 'form'%>

app/views/users/show.html.erb
<h2 class="text-center"> Welcome <%= @user.username %></h2>
<div class="row">
    <div class="col-md-4 offset-4 text-center">
        <%= gravatar_for @user, size: 150 %>
    </div>
</div>
<h4 class="text-center"><%= @user.username %>'s articles </h4>

<%= render 'articles/article', obj: @user_articles%>
<div class="offset-5 pl-4">
    <%= will_paginate @user_articles %>
</div>